#!/bin/bash
#
# =============================================================================
# OpenVox Installer - Control Repository Module
# =============================================================================
# Handles cloning the control repository and configuring Hiera.
#
# This module is responsible for:
#   - Cloning the control repo from the supplied URL
#   - Setting up environment directory structure
#   - Configuring hiera.yaml to use control repo data
#   - Ensuring proper file ownership and permissions
#
# Requires: r10k_remote config value (Git URL)
# =============================================================================

# =============================================================================
# SECTION: Control Repository Deployment
# =============================================================================

deploy_control_repo() {
    log_info "=========================================="
    log_info "Deploying Control Repository"
    log_info "=========================================="
    
    if [[ -z "$r10k_remote" ]]; then
        log_fatal "Control repo requires r10k_remote (Git URL)"
    fi
    
    log_info "Control repository: $r10k_remote"
    
    local environments_dir="/etc/puppetlabs/code/environments"
    local hiera_path="/etc/puppetlabs/puppet/hiera.yaml"
    
    # Clone control repo if not already present
    clone_control_repo "$environments_dir"
    
    # Configure hiera.yaml
    configure_hiera "$environments_dir"
    
    # Set proper ownership
    set_repo_ownership "$environments_dir"
    
    log_info "Control repository deployment complete"
}

# =============================================================================
# SECTION: Clone Control Repository
# =============================================================================

clone_control_repo() {
    local target_dir="$1"
    
    log_info "Cloning control repository to $target_dir..."
    
    # Check if environments directory already has content
    if [[ -d "$target_dir" ]] && [[ -n "$(ls -A "$target_dir" 2>/dev/null)" ]]; then
        log_info "Environments directory exists, checking for existing control repo..."
        
        # Check if it's a git repo
        if [[ -d "$target_dir/.git" ]]; then
            log_info "Existing git repo found, pulling latest..."
            cd "$target_dir"
            git pull origin main 2>/dev/null || git pull origin master 2>/dev/null || true
            cd - > /dev/null
            return 0
        else
            log_info "Directory exists but not a git repo, backing up..."
            mv "$target_dir" "${target_dir}.bak.$(date +%s)"
        fi
    fi
    
    # Create parent directory
    mkdir -p "$(dirname "$target_dir")"
    
    # Clone the repository
    if [[ -x /opt/puppetlabs/puppet/bin/git ]]; then
        /opt/puppetlabs/puppet/bin/git clone "$r10k_remote" "$target_dir"
    elif command -v git &>/dev/null; then
        git clone "$r10k_remote" "$target_dir"
    else
        log_fatal "Git not found - cannot clone control repository"
    fi
    
    log_info "Control repository cloned successfully"
}

# =============================================================================
# SECTION: Configure Hiera
# =============================================================================
# Configures hiera.yaml to use the control repo's data directory.
# Creates a standard Hiera 5 configuration with:
#   - Per-node data lookup
#   - Per-environment data
#   - Common data fallback

configure_hiera() {
    local environments_dir="$1"
    local hiera_path="/etc/puppetlabs/puppet/hiera.yaml"
    
    log_info "Configuring Hiera..."
    
    # Check if control repo has its own hiera.yaml
    local repo_hiera="$environments_dir/production/hiera.yaml"
    if [[ -f "$repo_hiera" ]]; then
        log_info "Control repo contains hiera.yaml, copying..."
        cp "$repo_hiera" "$hiera_path"
    else
        log_info "Creating default hiera.yaml..."
        cat > "$hiera_path" << 'HIERAYAML'
# Hiera 5 Configuration
# Generated by OpenVox Installer
# This file is managed - edit with care

version: 5

defaults:
  datadir: data
  data_hash: yaml_data

hierarchy:
  - name: "Per-node data"
    path: "nodes/%{trusted.certname}.yaml"

  - name: "Per-environment data"
    path: "%{environment}.yaml"

  - name: "Common data"
    path: "common.yaml"
HIERAYAML
    fi
    
    # Create data directory structure
    local data_dir="$environments_dir/production/data"
    mkdir -p "$data_dir/nodes"
    
    # Create default common.yaml if not present
    if [[ ! -f "$data_dir/common.yaml" ]]; then
        cat > "$data_dir/common.yaml" << 'COMMONYAML'
# Common Hiera Data
# Add shared configuration here

classes: []
parameters: {}
COMMONYAML
    fi
    
    log_info "Hiera configured at $hiera_path"
}

# =============================================================================
# SECTION: Set Repository Ownership
# =============================================================================

set_repo_ownership() {
    local target_dir="$1"
    
    log_info "Setting ownership on $target_dir..."
    
    # Set ownership to puppet user
    if getent passwd puppet > /dev/null 2>&1; then
        chown -R puppet:puppet "$target_dir"
    fi
    
    # Ensure proper permissions
    chmod -R 755 "$target_dir"
    
    log_info "Ownership set"
}

# =============================================================================
# SECTION: Validate Control Repo Structure
# =============================================================================

validate_control_repo() {
    local environments_dir="/etc/puppetlabs/code/environments"
    
    if [[ ! -d "$environments_dir" ]]; then
        log_error "Environments directory not found: $environments_dir"
        return 1
    fi
    
    # Check for at least production environment
    if [[ ! -d "$environments_dir/production" ]]; then
        log_warn "Production environment not found"
        return 1
    fi
    
    # Check for Puppetfile
    if [[ ! -f "$environments_dir/production/Puppetfile" ]]; then
        log_warn "Puppetfile not found in production environment"
    fi
    
    log_info "Control repo structure validated"
    return 0
}
