#!/bin/bash
#
# =============================================================================
# ovinstall - OpenBolt Installation
# =============================================================================
# Installs and configures OpenBolt (Bolt) for agentless orchestration.
# Requires: functions.sh (logging, package helpers)
# =============================================================================

install_openbolt() {
    log_info "=========================================="
    log_info "Installing OpenBolt"
    log_info "=========================================="

    install_package openbolt

    configure_openbolt

    log_info "OpenBolt installed successfully"
}

configure_openbolt() {
    log_info "Configuring OpenBolt..."

    local bolt_dir="/etc/puppetlabs/bolt"
    mkdir -p "$bolt_dir/plugins"

    local hostname="${server_hostname:-localhost}"

    # Create bolt-project.yaml configuration
    cat > "$bolt_dir/bolt-project.yaml" << EOF
# OpenBolt (Bolt) project configuration
# Generated by ovinstall

# Modulepath for modules to use with bolt
modulepath:
  - /etc/puppetlabs/code/environments/production/modules
  - /etc/puppetlabs/code/modules

# Inventory file for managing nodes
inventoryfile: $bolt_dir/inventory.yaml

# SSH configuration
ssh:
  host-key-check: false  # Set to true in production
  connect-timeout: 30

# Run-as configuration
run-as: root

# Plugin directory
plugin-dirs:
  - $bolt_dir/plugins

# PuppetDB configuration for facts
puppetdb:
  server_urls:
    - https://${hostname}:8081
  cacert: /etc/puppetlabs/puppet/ssl/certs/ca.pem
  cert: /etc/puppetlabs/puppet/ssl/certs/${hostname}.pem
  key: /etc/puppetlabs/puppet/ssl/private_keys/${hostname}.pem
EOF

    # Create inventory.yaml
    cat > "$bolt_dir/inventory.yaml" << EOF
# Bolt inventory
# Generated by ovinstall
# Add your managed nodes here

groups:
  - name: openvox_servers
    targets:
      # Add your nodes here
      # - name: node1.example.com
      #   alias: webserver
      # - name: node2.example.com
      #   config:
      #     ssh:
      #       host: 192.168.1.20
      #       user: root
    config:
      transport: ssh
      ssh:
        host-key-check: false
EOF

    log_info "OpenBolt configuration complete"
}

# Verify OpenBolt installation
verify_openbolt() {
    if command -v bolt &>/dev/null; then
        log_info "OpenBolt version: $(bolt --version)"
    else
        log_warn "OpenBolt command not found in PATH"
    fi
}
