#!/bin/bash
#
# OpenVox Installer - OpenBolt Installation
#

install_openbolt() {
    log_info "=========================================="
    log_info "Installing OpenBolt"
    log_info "=========================================="
    
    # Install OpenBolt package
    case "$PACKAGE_MANAGER" in
        yum)
            yum install -y openbolt
            ;;
        apt)
            apt-get install -y openbolt
            ;;
    esac
    
    # Configure OpenBolt
    configure_openbolt
    
    log_info "OpenBolt installed successfully"
}

configure_openbolt() {
    log_info "Configuring OpenBolt..."
    
    local bolt_dir="/etc/puppetlabs/bolt"
    mkdir -p "$bolt_dir"
    
    # Create bolt.yaml configuration
    cat > "$bolt_dir/bolt.yaml" << EOF
# OpenBolt (Bolt) configuration
# Generated by OpenVox Installer

# Modulepath for modules to use with bolt
modulepath: /etc/puppetlabs/code/environments/production/modules:/etc/puppetlabs/code/modules

# Inventory file for managing nodes
inventoryfile: $bolt_dir/inventory.yaml

# SSH configuration
ssh:
  host-key-check: false  # Set to true in production
  connect-timeout: 30

# Run-as configuration
run-as: root

# Plugin directory
plugin directory: $bolt_dir/plugins

# Puppetsdb configuration for facts
puppetdb:
  urls:
    - https://${server_hostname:-localhost}:8081
  cacert: /etc/puppetlabs/puppet/ssl/certs/ca.pem
  cert: /etc/puppetlabs/puppet/ssl/certs/${server_hostname:-localhost}.pem
  key: /etc/puppetlabs/puppet/ssl/private_keys/${server_hostname:-localhost}.pem
EOF

    # Create inventory.yaml
    mkdir -p "$bolt_dir"
    cat > "$bolt_dir/inventory.yaml" << EOF
# Bolt inventory
# Generated by OpenVox Installer
# Add your managed nodes here

groups:
  - name: openvox_servers
    targets:
      # Add your nodes here
      # - name: node1.example.com
      #   alias: webserver
      # - name: node2.example.com
      #   config:
      #     ssh:
      #       host: 192.168.1.20
      #       user: root
    config:
      transport: ssh
      ssh:
        host-key-check: false
EOF

    # Create plugins directory
    mkdir -p "$bolt_dir/plugins"
    
    log_info "OpenBolt configuration complete"
}

# Verify OpenBolt installation
verify_openbolt() {
    if command -v bolt &>/dev/null; then
        log_info "OpenBolt version: $(bolt --version)"
    else
        log_warn "OpenBolt command not found in PATH"
    fi
}
