#!/bin/bash
#
# =============================================================================
# ovinstall - Server Installation
# =============================================================================
# Installs and configures openvox-server (PuppetServer).
# Requires: functions.sh (logging, package helpers, OS detection)
# =============================================================================

install_server() {
    log_info "=========================================="
    log_info "Installing OpenVox Server"
    log_info "=========================================="

    install_package openvox-server

    configure_server

    log_info "Starting PuppetServer..."
    systemctl start puppetserver
    if ! wait_for_port "127.0.0.1" 8140 120; then
        log_fatal "PuppetServer did not open port 8140 within 120s"
    fi

    log_info "OpenVox Server installed successfully"
}

configure_server() {
    log_info "Configuring OpenVox Server..."

    local puppet_bin="/opt/puppetlabs/bin/puppet"
    if [[ ! -x "$puppet_bin" ]]; then
        puppet_bin="puppet"
    fi

    # Configure server hostname
    if [[ -n "${server_hostname:-}" ]]; then
        log_info "Setting server hostname to: $server_hostname"
        "$puppet_bin" config set server "$server_hostname" --section main
    fi

    # Configure Java heap memory (-Xmx = max heap, -Xms = initial heap)
    local jvm_mem="${jvm_memory:-2g}"
    if [[ -f /etc/sysconfig/puppetserver ]]; then
        sed -i "s/^JAVA_ARGS=.*/JAVA_ARGS=\"-Xmx${jvm_mem} -Xms${jvm_mem} -Djruby.logger.class=org.jruby.RubyDefaultLog\"/" /etc/sysconfig/puppetserver
    fi

    # PuppetDB integration (server mode always includes PuppetDB)
    "$puppet_bin" config set reports puppetdb --section main
    "$puppet_bin" config set storeconfigs true --section main
    "$puppet_bin" config set storeconfigs_backend puppetdb --section main

    # Without routes.yaml + puppetdb.conf, storeconfigs silently fails to use PuppetDB
    configure_puppetdb_terminus

    # Configure environmentpath and codedir
    "$puppet_bin" config set environmentpath /etc/puppetlabs/code/environments --section main
    "$puppet_bin" config set codedir /etc/puppetlabs/code --section main

    log_info "Server configuration complete"
}

# Write PuppetDB terminus wiring so storeconfigs/reports actually reach PuppetDB.
configure_puppetdb_terminus() {
    local confdir="/etc/puppetlabs/puppet"
    local routes="${confdir}/routes.yaml"
    local pdb_conf="${confdir}/puppetdb.conf"
    local pdb_host="${server_hostname:-localhost}"

    mkdir -p "$confdir"

    cat > "$routes" << 'ROUTESEOF'
---
master:
  facts:
    terminus: puppetdb
    cache: yaml
ROUTESEOF

    cat > "$pdb_conf" << PDBEOF
# Generated by ovinstall — PuppetDB client settings for the compiler
[main]
server_urls = https://${pdb_host}:8081
PDBEOF

    chmod 0644 "$routes" "$pdb_conf"
    log_info "Wrote PuppetDB terminus wiring: ${routes} and ${pdb_conf} (server_urls host: ${pdb_host})"
}
